site_name: LEGO Python Robotics Docs
site_url: http://mathewmaki.github.io/lego-robotics-day-camp/

theme:
  name: "material"

plugins:
  - mkdocstrings

extra_css:
  [css/extra.css]

nav:
  - Python Documentation: index.md
  - Code Examples: examples.md

docs_dir: docs
site_dir: site
