name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install MkDocs and required plugins
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocstrings
          pip install "mkdocstrings[python]"

      
      - name: Build and Deploy Mkdocs
        run: |
          mkdocs build --clean
          mkdocs gh-deploy --force --verbose
